### ISSUE TITLE
Get-PartnerSignInActivity issue

### ISSUE THREAD

**Issue by kevinbasoftcat** [microsoft/Partner-Center-PowerShell#194]
# Steps to reproduce
https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnerusersigninactivity?view=partnercenterps-2.0

> What steps can reproduce the defect?
With the latest version .4 we are now getting all user's returned when using the Get-PartnerUser however when running the second part of the sign in activity commands we are getting the below error.

Get-PartnerUserSignInActivity : Code: generalException
Message: An error occurred sending the request.
At line:1 char:31
+ ... rs.ForEach({Get-PartnerUserSignInActivity -StartDate (Get-Date).AddDa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerUserSignInActivity], ServiceException
    + FullyQualifiedErrorId : Microsoft.Graph.ServiceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerUserSignInActivity

> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version 2.0.1911.4

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat would you mind sharing the details on how you authenticating and actual commands you running to get this error?

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

I am authenticating using my global admin username and password that is an admin agent in our partner account. The commands I am running are from Example 6 in the below.

https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnerusersigninactivity?view=partnercenterps-2.0

Thanks,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat thank you for the quick response. Just to confirm you are running `Connect-PartnerCenter` without any parameters when connecting correct? 

If that is the case, then this issue for certain is not caused by authentication. Which means that Microsoft Graph is throwing an error in your circumstance, that is not being handled. To help isolate this error would you be able to run [Fiddler](https://www.telerik.com/fiddler) to capture the request and full error when making this request?

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

I am wandering if the issue was me running this in the background while doing other things on the same machine. I have just spun up an Azure VM to run it from and am running fiddler alongside the command to record the logs. As we have 4000+ users the command takes a long time to run and error so I will update you once it completes or errors with the fiddler logs.

Thanks,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat thank you for helping troubleshoot this, and smart thinking on using a virtual machine. There should not be an impact of you doing operations in the background, but it will be interesting to see what you discover.

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

The command started to error so I stopped it and saved the fiddler log which is available in the attached. Please let me know If you need anything else.

Kind Regards,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
Hi @kevinbasoftcat, thank you for you helping with this. It does not look like the attachment came through. Can you email it to isaiah.williams@microsoft.com?

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

Just sent them over using a shared link from my One Drive so that should come through to your email address any issues let me know.

Thanks,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat I just released version [2.0.1911.5](https://www.powershellgallery.com/packages/PartnerCenter/2.0.1911.5) that contains a handful of enhancements. When you get an opportunity can you update to this version and try again?

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

I installed the latest version and ran the commands again with fiddler also running. Below is the link to the fiddler logs and the Resolve-PartnerError command as the errors started appearing after about 20-30 minutes.

https://softcat-my.sharepoint.com/:u:/p/kevinba/EXM0i96zLLNAsLUiBUHPP1MBs8fROY38MDKTnjmT0HsWKw?email=isaiah.williams%40microsoft.com&e=PQKHM2

Please let me know if you need anything else.

Kind Regards,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat I having issue accessing the link you shared. Would it be possible for you to email the zip file to isaiah.williams@microsoft.com?

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat thank you for sharing the details with me. I have been digging into this further and discovered what I believe to be the root cause for the issue. The required code changes have been made and the hope is to have an update available through the PowerShell gallery before the end of the year.

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

Thank you for the updates. Based on the below I assume the new version 3.0 will still have the same issues so should I wait for the new code to be released or try using the version 3.0 release?

Kind Regards,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat version [3.0.1](https://www.powershellgallery.com/packages/PartnerCenter/3.0.1) of the module has been released. It includes a handful of enhancements that should resolve the root cause of this issue. Would you be able to update and try the following? 

1. Run the command as you have been. I am interested to know if you are still encountering the thread pool starvation issue
2. If you encounter issues with the above restart the machine and try the details documented below
3. Run the following command 

```powershell
Get-PartnerUserSignInActivity -StartDate (Get-Date).AddDays(-7)
```

Thank you for helping us test and validate everything is working as excepted.

**Comment by kevinbasoftcat** [comment]
Thanks Isaiah I have downloaded the new version and am testing on my Azure machine now. Will let you know how it goes.

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

Checking after lunch and the errors have returned. I then tried your other command but get the general exception error for that as well see below. Please let me know if you need me to grab any fiddler logs.

Thanks,
Kevin Barlow

[cid:image002.png@01D5B0EE.0D636360]

From: Kevin Barlow
Sent: 12 December 2019 11:52
To: microsoft/Partner-Center-PowerShell <reply@reply.github.com>; microsoft/Partner-Center-PowerShell <Partner-Center-PowerShell@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoft/Partner-Center-PowerShell] Get-PartnerSignInActivity issue (#194)

Thanks Isaiah I have downloaded the new version and am testing on my Azure machine now. Will let you know how it goes.

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat I have good news, the root cause for this issue has been identified. Through issue #230 I was able to isolated what was happening. Currently I am trying to wrap up the solution needed to resolve this issue

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

Perfect thank you for the update. If you could let me know when you want me to test I can carry out testing for you.

Kind Regards,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat version [3.0.2](https://www.powershellgallery.com/packages/PartnerCenter/3.0.2) was just released. The only change included in that release was an update that addressed the root cause of this issue. Before I close this issue I was hoping that you could test to verify that everything is working as expected for you.

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

Thank you for the update I have tested and the command is now working without generating any errors so thank you for your persistence in getting this resolved.

I do however have 1 further query as the line after the logon activities are obtained to display API activities without MFA returns blank even though we have API calls being made without MFA. Is this expected behaviour?

https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnerusersigninactivity?view=partnercenterps-2.0
$activities | ? {$_.AuthenticationDetails | ? {$_.Succeeded -eq $true}} | ? {$_.MfaDetail -eq $null} | ? {$_.ResourceId -eq 'fa3d9a0c-3fb0-42cc-9193-47c7ecd2edbd'}

Kind Regards,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat this is particular interesting question because it will depend on a number of factors. This type of result could be due to one of the following scenarios

1. Your integration has not perform any operations in the last seven days
2. Your integration is leveraging a persistent token cache, which the token is being updated when expired instead of regenerated. This type of event is not available through the sign-in activities
3. Your integration is leveraging the Secure Application Model, which is similar to behavior described in scenario two
4. Your integration is leveraging app-only authentication (this is where a client identifier and secret key are used to get an access token), this type authentication is not captured in the sign-in activity logs.

If you the above scenarios do not apply to your integration, then it would be worth looking at the sign-in activities in Azure AD for the an account you know that is being used. That way you can verify that there is not an issue.

**Comment by isaiahwilliams** [comment]
If you have further concerns or issues please let us know.
