### ISSUE TITLE
Azure token request returns consent error

### ISSUE THREAD

**Issue by jmeilleur1** [microsoft/Partner-Center-PowerShell#311]
We are able to use our refresh token to generate a new token for Partner Center access with this command:
New-PartnerAccessToken -ApplicationId $ApplicationId -RefreshToken $RefreshToken -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Credential $Credential -Tenant $PCTenantId

However when we try to use the same refresh token to generate a token to access our customer Azure subscriptions with this command:
New-PartnerAccessToken -ApplicationId $ApplicationId -Credential $credential -RefreshToken $refreshToken -Scopes 'https://management.azure.com/user_impersonation' -ServicePrincipal -Tenant $CustomerId

It returns an error 
AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxxx-xxxx-xxxxx-xxxxxx-xxxx' named 'Partner Center Web App 2020 v3'. Send an interactive authorization request 

## Expected behavior
It  should return the access token

## Actual behavior

AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxxx-xxxx-xxxxx-xxxxxx-xxxx' named 'Partner Center Web App 2020 v3'. Send an interactive authorization request 

## Environment

PS Version 5.1.14409.1018
Partnercenter Module  3.0.9

**Comment by isaiahwilliams** [comment]
@jmeilleur1 based on the information that you shared, the Azure Active Directory application will need to be configured for pre-consent or you will need to perform the consent interactively. Perform the following if you are looking to configure the application for pre-consent 

```powershell
# Connect using partner credentials 
Connect-AzureAd 

$group = Get-AzureADGroup -Filter "displayName eq 'Adminagents'"
$sp = Get-AzureADServicePrincipal -Filter "appId eq '{yourAppsAppId}'"
Add-AzureADGroupMember -ObjectId $group.ObjectId -RefObjectId $sp.ObjectId
```

After doing this the issue you described above should be resolved.

**Comment by jmeilleur1** [comment]
@isaiahwilliams Thank you for the feedback.  I have validated that the Service Principal was already a member of the group.  I also tried removing the the SP from the group and adding again.  I can see it there referencing the correct AppID but it still throws the same error. 

Do you have any other suggestions?

**Comment by isaiahwilliams** [comment]
@jmeilleur1 since the service principal for the application you are using is already a member of the admin agents group, then it should be configured for pre-consent. Usually when this error persists after that configuration it is caused by one of the following 

- You are using an application in a different tenant that does not have a relationship with the customer
- You do not have an active delegated admin privilege (DAP) relationship between the partner and customer 

If the above does not apply and you are able to access Azure PowerShell for other customers, then you might want to manually create this single service principal in the customers environment. I know this is not ideal, but in the past I have seen this error was only able to solve it by creating a new application (and ensuring it is configured for pre-consent) or manually creating the service principal in the customer's tenant.

**Comment by isaiahwilliams** [comment]
If you are still having issues with this, then I would recommend open support ticket with Microsoft support.
