### ISSUE TITLE
Get-partnerinvoice, Get-PartnerInvoiceLineItem, get-partnerazureratecard - a task was canceled

### ISSUE THREAD

**Issue by aconn21** [microsoft/Partner-Center-PowerShell#312]
Last few days I've been getting these errors

Get-PartnerInvoiceLineItem : A task was canceled.
Get-PartnerInvoice : A task was canceled.
Get-PartnerAzureRateCard : A task was canceled.

It seems there is an issue on Microsoft's end but I don't see anything on the status alerts in the partner center portal. 

I've run the latest version of the module and an older verison of the module with the same results on my PC and servers running in Azure. The Get-partnerinvoice* commands are failing about 80-90% of the time. 

I've logged a ticket with Microsoft Partner Support but have had no response. Anyone here able to help? I'm in the Australia Southeast region, not sure if its a regional issue. Any information or assistance would be appreciated.

**Comment by isaiahwilliams** [comment]
@aconn21 I am not aware of any issue that would be impacting these commands. However, you will be able to get the actual error code returned from the API by running the commands with the `-Debug` parameter. That should help shed light on what exactly is happening. It is possible that the HTTP operations are timing out, but I cannot for certain based on the above information.

**Comment by aconn21** [comment]
It seems to be getting worse. It's clear there is an issue on Microsoft's end. Even connecting is a problem now: Connect-PartnerCenter : A task was canceled.

I managed to run a -Debug on one of the commands, see below. It just hangs on the GET for a while and then outputs the error at the bottom.

  "links": {
    "self": {
      "uri": "/invoices",
      "method": "GET",
      "headers": []
    }
  },
  "attributes": {
    "objectType": "Collection"
  }
}

DEBUG: [AccessTokenAuthenticator] The specified access token expires at 24/06/2020 6:06:41 AM
DEBUG: [AccessTokenAuthenticator] The specified access token expires at 24/06/2020 6:06:41 AM
DEBUG: [AccessTokenAuthenticator] Constructing the authentication result based on the specified access token
DEBUG: [AccessTokenAuthenticator] Constructing the authentication result based on the specified access token
DEBUG: [AccessTokenAuthenticator] The UPN claim value is **RemovedUsername**
DEBUG: [AccessTokenAuthenticator] The UPN claim value is **RemovedUsername**
DEBUG: [AccessTokenAuthenticator] Constructing the resource account value based on specified access token
DEBUG: [AccessTokenAuthenticator] Constructing the resource account value based on specified access token
DEBUG: ============================ HTTP REQUEST ============================
HTTP Method:
GET

Absolute Uri:
https://api.partnercenter.microsoft.com/v1/invoices/**RemovedInvoiceID**/lineitems/Azure/BillingLineItems

Headers:
Accept                        : application/json
MS-PartnerCenter-Client       : Partner Center PowerShell
MS-CorrelationId              : 00000000-0000-0000-0000-000000000000
X-Locale                      : en-US
MS-RequestId                  : ea3b885b-3b5d-4098-8d50-021ffd929680
MS-SdkVersion                 : 1.15.6.0

DEBUG: ============================ HTTP REQUEST ============================
HTTP Method:
GET

Absolute Uri:
https://api.partnercenter.microsoft.com/v1/invoices/**RemovedInvoiceID**/lineitems/Azure/BillingLineItems

Headers:
Accept                        : application/json
MS-PartnerCenter-Client       : Partner Center PowerShell
MS-CorrelationId              : 00000000-0000-0000-0000-000000000000
X-Locale                      : en-US
MS-RequestId                  : ea3b885b-3b5d-4098-8d50-021ffd929680
MS-SdkVersion                 : 1.15.6.0

Get-PartnerInvoiceLineItem : A task was canceled.

**Comment by isaiahwilliams** [comment]
@aconn21 thank you for sharing this information. I have reached out to the Partner Center API team, to get their help investigating this issue. Out of curiosity does this error happen for all invoices or just a specific one?

**Comment by aconn21** [comment]
Any invoice. I found the easiest way to replicate the errors it is to just put a bunch of the commands in a loop. Example below, anyone of those commands will give the error. Unless of course you get the error on Connect-PartnerCenter then the whole thing will break

Import-Module PartnerCenter

Connect-PartnerCenter -AccessToken $PCToken.AccessToken -TenantId $PartnerTenant
while($true)
{

    $RateCard = Get-PartnerAzureRateCard -Currency 'AUD' -Region 'AU'
    $AllInvoices = Get-PartnerInvoice
    $AzureInvoices = $AllInvoices | where {$_.InvoiceType -eq "Recurring"} | sort InvoiceDate -Descending
    $OneTimeInvoices = $AllInvoices | where {$_.InvoiceType -eq "OneTime"} | sort InvoiceDate -Descending
    $LatestInvoice = $AzureInvoices[0]
    $AllInvoiceItems = Get-PartnerInvoiceLineItem -invoiceid $LatestInvoice.InvoiceId -billingprovider Azure -LineItemType BillingLineItems -CurrencyCode AU
    $OfficeInvoiceItems = Get-PartnerInvoiceLineItem -invoiceid $LatestInvoice.InvoiceId -billingprovider Office -LineItemType BillingLineItems -CurrencyCode AU
    $OneTimeInvoiceItems = Get-PartnerInvoiceLineItem -invoiceid $OneTimeInvoices[0].InvoiceId -BillingProvider OneTime -LineItemType BillingLineItems -CurrencyCode AU
    get-date | select DateTime
}

**Comment by isaiahwilliams** [comment]
@aconn21 thank you for sharing this level of details. If this works for approximately a hour, then I think I see what is happening. Access tokens are only valid for a hour. So, I am suspecting the actual error stating the access token has expired is being masked. Does the issue happen when you connect using the following?

```powershell
$refreshToken = '<refreshToken>'
Connect-PartnerCenter -ApplicationId 'xxxx-xxxx-xxxx-xxxx' -RefreshToken $refreshToken
```

Note you will need to replace the application identifier value above with the identifier of the application you used to generate the refresh token.

**Comment by aconn21** [comment]
No I don't need to run it for more than an hour to get the errors. It's an issue on Microsoft's end. If you really wanted to run it for more than an hour, you could modify the loop.

$ReAuthTimer = [system.diagnostics.stopwatch]::StartNew()

while($true)
{
    #Job running for more than 1 hour need to re-auth
    if($ReAuthTimer.Elapsed.Minutes -ge 50)
    {
        $PCToken = New-PartnerAccessToken -RefreshToken $RefreshToken -Credential $App_Cred -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -TenantId $PartnerTenant
        Connect-PartnerCenter -AccessToken $PCToken.AccessToken -TenantId $PartnerTenant

        $ReAuthTimer.reset()
        $ReAuthTimer.Start()
    }

**Comment by isaiahwilliams** [comment]
@aconn21 what I am trying to isolate is whether or not the issue is with the Partner Center API or the module itself. So, it is helpful to know that you are not encountering an issue due to an expired access token. Since the error you are receiving is that a task has been cancelled it is difficult to say with certainty where the issue resides. If you could recreate the error one more time and then share the output from 

```powershell
Resolve-PartnerError
``` 

That should shed some light on what exactly is happening. Also, can you share what version of the module you are using?

**Comment by aconn21** [comment]
I've tried different module versions to no success. At the moment I'm
trying module version 3.0.9. Here is the debug info from
Resolve-PartnerError:

Exception        : System.Threading.Tasks.TaskCanceledException: A task was
canceled.
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<HandleResponseAsync>d__38`1.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__24`1.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__21`1.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Invoices.InvoiceLineItemCollectionOperations.<GetAsync>d__3.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerInvoiceLineItem.<<ExecuteCmdlet>b__16_0>d.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.PowerShell.Utilities.ConcurrencyTaskScheduler.<RunConcurrentTaskAsync>d__21.MoveNext()
HelpLink         :
Message          : A task was canceled.
StackTrace       :    at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<HandleResponseAsync>d__38`1.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__24`1.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__21`1.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.Invoices.InvoiceLineItemCollectionOperations.<GetAsync>d__3.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerInvoiceLineItem.<<ExecuteCmdlet>b__16_0>d.MoveNext()
                   --- End of stack trace from previous location where
exception was thrown ---
                      at
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
                      at
Microsoft.Store.PartnerCenter.PowerShell.Utilities.ConcurrencyTaskScheduler.<RunConcurrentTaskAsync>d__21.MoveNext()
ErrorCategory    : CloseError: (:) [Get-PartnerInvoiceLineItem],
TaskCanceledException
ErrorDetails     :
InvocationInfo   : System.Management.Automation.InvocationInfo

**Comment by isaiahwilliams** [comment]
@aconn21 based on the information you have provided there is a chance this issue is related to a client side HTTP timeout. Through the upcoming release the timeout is being expanded which should resolve this issue.

**Comment by aconn21** [comment]
The same issue happens in the partner center portal via the web. It just
times out, often, when doing anything in the billing section of the portal.
Seems to me the issues are related. This needs to be fixed ASAP.

**Comment by isaiahwilliams** [comment]
@aconn21 version 3.0.10 of the module was just released, and that update includes a change to the HTTP timeout. This change should help contend with the server latency that you are observing. As it relates to the issues you mentioned with Partner Center, I would recommend that you open a support ticket. This module is supported by the partner community and is dependent on the Partner Center API. Since you are seeing issues with Partner Center itself, this means you can engage the Microsoft support teams to drive that underlying problem to a resolution.

**Comment by aconn21** [comment]
Thanks I can confirm this has fixed the issue.

**Comment by pheeling** [comment]
Hi @aconn21 I still get the same issue with Get-PartnerCustomerSubscription after aprox. 15min or a certain amount of requests connection gets closed. 
| Unable to read data from the transport connection: The
     | connection was closed.

How did exactly overcome this issue with version 3.0.10?

thanks for a feedback.

Best regards Philipp
