### ISSUE TITLE
Connect-PartnerCenter -AccessToken not working in  1.5.1902.1

### ISSUE THREAD

**Issue by Agazoth** [Microsoft/Partner-Center-PowerShell#68]
# Steps to reproduce
```Powershell
$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -ServicePrincipal
$refreshToken = $token.RefreshToken
$pcToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -Credential $credential
Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationId $ClientAppId -TenantId $TenantID
Connect-PartnerCenter : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-PartnerCenter], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Store.PartnerCenter.PowerShell.Commands.ConnectPartnerCe
   nter
```
## Expected behavior

Should connect to PartnerCenter

## Actual behavior

It throws an error (the -AccessToken parameter is not in the cmdlet)

## Diagnostic logs

Please supply commands to produce. Then I'd be glad to upload.

## Environment
```powershell
Name             : ConsoleHost
Version          : 5.1.17763.134
InstanceId       : fff38cbd-abe3-452b-b06c-046b420db12e
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

Tested in:
```Powershell
Name             : ConsoleHost
Version          : 6.2.0-preview.3
InstanceId       : 445eab07-cb4b-41cd-a231-5d1f36b439bc
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```
Same result.

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

We just merged an update that will address issues #67 and #68. The plan is to release version 1.5.1902.2 later today. This update will contain a fix for both issues.

**Comment by Agazoth** [comment]
Excellent. Thanks!

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

We have just released version 1.5.1902.2 which includes a fix for this issue. Please let us know if you discover any other issues.

**Comment by Crazyabout** [comment]
@Agazoth Can i Ask how you get it working with connecting to the partner center through the "Connect-Partnercenter" without providing credentials every time you run the script.
My goal atm is to get a script where i get usage data and that will run monthly without user interaction every time when the script runs.
So a get-credential is not exactly efficient. And the accessToken expires after one hour for some reason

Any help to implement this ?

**Comment by Agazoth** [comment]
Hi @Crazyabout 
I save the RefreshToken in an Azure Key Vault and use a Managed Service Instance to retrieve the key. Guess you can save the RefreshToken in a file somewhere, but that is of course up to your security requirements.

I use the Refreshtoken to generate a new token with by running this command:
New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -ApplicationId $ClientAppId

I also keep the ClientAppId in an Azure Key Vault.

In Powershell you can actually store the credential object (pretty) secure on your disk. Once you have generated the credentialset, you can export it to clixml. The exported credential object can be re-imported by the user that exported the credential object on the machine. I used this technique a lot before I went all Cloud.

Since scripts typically run under service accounts, you would have to do a runas on a Powershell console to save the credentialset under the serviceaccount context.

**Comment by Crazyabout** [comment]
ATM i try the folowing but still get issues at the get credentials (it still pops up to ask me my credential) and even if i provide a valid credential. My connect center command fails by asking for application id , expired on value. even if that's not part of the command parameters in the docs .
Can't seem to see what i am doing wrong. I guess the credentials part is not at his best and the way i connect to my partner center can be wrong either
```

#Get credentials
$appId = 'xxxxxxxxxxxxxxxxxxx'
$appSecret = 'xxxxxxxxxxxxxxxx' | ConvertTo-SecureString -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ($appId , $appSecret)


#$credential = New-Object System.Management.Automation.PSCredential $appId, $appSecret
$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -ServicePrincipal

#this could also be saved in a keyvault but for testing I will do this like this.
 $token.RefreshToken | Out-File "C:\refresh.txt"
 $refreshToken = Get-Content "C:\refresh.txt"


$pcToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -Credential $credential
$tenantId = 'cccc'

Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationId $appId 
```

**Comment by Crazyabout** [comment]
How long is the refreshtoken available. 
I tried your solution but I have some questions about the expire date about it. 
I save the expiry date and the refresh token from the token in a txt file (for testing afterwords this will get like you said in a keyvault for a more secure env) 

`$Newtoken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -ApplicationId $appId
Connect-PartnerCenter -AccessToken $token.AccessToken -ApplicationId $appId -AccessTokenExpiresOn $Expires -TenantId $tenantId`

This is my new way of getting the accesstoken from the refreshtoken , but the accesstoke expires on if that date expires (tomorrow) will this be a problem than ? 
If i didn't provide this parameters command line asksk me for it.

**Comment by Agazoth** [comment]
I have been using the same refreshtoken for 2 weeks now. I have no idea how long it is going to be valid :-)

I think you should update to the latest version of the module. The AccessTokenExpiresOn parameter is deprecated on the version I'm on:  1.5.1902.4

**Comment by Crazyabout** [comment]
@Agazoth 
Already tried that with the Command
`Update-Module -Name PartnerCenter -Force`

**Comment by Crazyabout** [comment]
@Agazoth 
![image](https://user-images.githubusercontent.com/45975657/52866236-92139100-313e-11e9-844e-f0259a552fdb.png)
![image](https://user-images.githubusercontent.com/45975657/52866306-aa83ab80-313e-11e9-9c63-1e44ec2f2a6f.png)


Strange , I tried to update and the module tells me that i already have the latest module 1.5.1902.4

**Comment by Crazyabout** [comment]
I deleted the AccessTokenExpiresOn parameter and now it didn't give any error for it. Don't know why it doesn't fail and an hour ago It gave one.
Always a pleasure when it works and you don't know why. Thnx !!!!! @Agazoth

**Comment by Crazyabout** [comment]
@Agazoth  @isaiahwilliams 
Is there any documentation or knowledge on how long the refresh token will work. So that i can know when to use a new one. For security reasons it may be good to change this once in a while. But I want to know what the default expiry date is. OR is that the entire cause of refresh token that this never fails ?

**Comment by isaiahwilliams** [comment]
Hi @Crazyabout, 

See [Active Directory configurable token lifetimes](https://docs.microsoft.com/azure/active-directory/develop/active-directory-configurable-token-lifetimes) for details regarding how long the refresh token is valid. Basically if you generate the refresh token using an Azure AD with a type of web/API the refresh token will be valid until it is revoked. That is if you use once every ninety days.
